### ISSUE TITLE
Error on wsus_miner 

### ISSUE THREAD

**Issue by amar3lo** [zbx-sadman/WSUS#1]
i got this erros on windows 2012 host with wsus 6.3 

 5199:20160407:164721.462 Sending [wsus.miner[Discovery,ComputerGroup]
At C:\Zabbix\wsus_miner.ps1:310 char:15
At C:\Zabbix\wsus_miner.ps1:310 char:15

i got no data in zabbix server side
this erros is from zabbix log.

can you help me?

**Comment by zbx-sadman** [comment]
Seems that yours Windows 2012 (do u have not **R2** - right?) got a problem with _Get-WsusServer_ cmdlet.

Lets try do debug...
Run from console on WSUS host _powershell -NoProfile -ExecutionPolicy "RemoteSigned" -File "wsus_miner.ps1" -Action "Get" -Object "Info" -Verbose -defaultConsoleWidth > log.txt_ and show to me _log.txt_ contents.

**Comment by amar3lo** [comment]
there it goes:

---

VERBOSE: 04/08/2016 08:49:56 Test 'UpdateServices' module state
VERBOSE: 04/08/2016 08:49:57 Trying to connect to local WSUS Server
Get-WsusServer : Request for principal permission failed.
At C:\Zabbix\wsus_miner.ps1:310 char:15
-               Get-WsusServer;
-               ~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidData: (Microsoft.Updat...usServerCommand: 
    GetWsusServerCommand) [Get-WsusServer], SecurityException
  - FullyQualifiedErrorId : UnexpectedError,Microsoft.UpdateServices.Command 
    s.GetWsusServerCommand

## WARNING: Connection failed

**Comment by amar3lo** [comment]
and yes, is R2 2012 windows

**Comment by zbx-sadman** [comment]
So, today i was install WSUS role to VM with WS2012R2 and run the script. No errors reached on my system. My test server is standalone, all settings of WSUS is default.

I think it is WSUS and Windows Server interaction issue and error message _Get-WsusServer : Request for principal permission failed_ was confirmed that. 

I've found the posts with same problem: https://social.technet.microsoft.com/Forums/office/en-US/e03c2c3a-c2d3-46b6-adc2-5a6de2fb898e/request-for-principal-permission-failed?forum=winserverwsus  & http://www.wsus.info/index.php?showtopic=11227

But i can't check posted solution, because haven't error. Try to apply recipe from this.forums to your system and inform me about the results. 

Thanks.

**Comment by amar3lo** [comment]
it works!!

i had to put the administrator group in the local wsus administration group.

thank you!

the script is awesome!

**Comment by amar3lo** [comment]
my happyness  dont last long..

everything works fine on wsus server, but in zabbix server a got the following error:

[root@zabbixserver ~]# zabbix_get -s wsusserver.mydomain -k wsus.miner[Get,LastSynchronization,StartTime]
Get-WsusServer : Exception of type
'Microsoft.UpdateServices.Administration.WsusInvalidServerException' was
thrown.
At C:\Zabbix\wsus_miner.ps1:310 char:15
-               Get-WsusServer;
-               ~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidData: (Microsoft.Updat...usServerCommand:
    GetWsusServerCommand) [Get-WsusServer], WsusInvalidServerException
  - FullyQualifiedErrorId : ServerIsInvalid,Microsoft.UpdateServices.Command
    s.GetWsusServerCommand

WARNING: Connection failed

the script works fine on powershell:

VERBOSE: 04/11/2016 10:48:05 Test 'UpdateServices' module state
VERBOSE: 04/11/2016 10:48:05 Trying to connect to local WSUS Server
VERBOSE: 04/11/2016 10:48:08 Connection established
VERBOSE: 04/11/2016 10:48:08 Creating collection of specified object: 'Info'
VERBOSE: 04/11/2016 10:48:08 Collection created, begin processing its with 
action: 'Get'
VERBOSE: 04/11/2016 10:48:08 Getting metric list due metric's Key not specified
VERBOSE: 04/11/2016 10:48:08 Finishing

my problem now lies on zabbix

**Comment by zbx-sadman** [comment]
Just for test try to change 'LocalSystem' account to yours (with wich script works) for 'Zabbix agent' Service (Computer Management -> Services), restart its and do _zabbix_get_ again.
