### ISSUE TITLE
The argument "wsus_miner.ps1" to the -File parameter does not exist

### ISSUE THREAD

**Issue by ferricena** [zbx-sadman/WSUS#3]
I was able to establish the connection between the zabbix server and the agent installed on the wsus server, but when I try to read the script, zabbix reports this message: 

The argument 'C:\zabbix-agent\scripts\wsus_miner.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.

The file path is correct, the same message occurs when I try to run the command in powershell by the wsus server:

PS C:\User\Administrador> powershell -NoProfile -ExecutionPolicy "RemoteSigned" -File "C:\zabbix-agent\scripts\wsus_miner.ps1" -Action "Get" -Object "Configuration" -Verbose
The argument 'C:\zabbix-agent\scripts\wsus_miner.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.

From what I understand zabbix finds the agent configuration file, it runs the UserParameters, but at the time of executing the script it does not recognize it.

**Comment by zbx-sadman** [comment]
Hello

I guess that is Powershell/Windows host issue, because 'File' option does not handled by the my .ps1 script.

Check filepath once more: `dir /b/a-d/s "C:\zabbix-agent\scripts\wsus_miner.ps1"`

**Comment by ferricena** [comment]
Hello

I have just started working with zabbix, this is the first agent I set up, I think I'm lost.

When entering the command it returns: 
Get-ChildItem : A positional parameter cannot be found that accepts argument '/s'.
At line:1 char :1: 
 dir /b /a -d /s "C:\zabbix-agent\scripts\wsus_miner.ps1"

        + CategoryInfo                  : InvalidArgument: (:) [Get-ChildItem], ParameterBindingException
         + FullyQualifiedErrorId      : PositionalParameterNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

**Comment by zbx-sadman** [comment]
Ough...
`dir` is not PowerShell function, run it from command prompt (cmd.exe).

**Comment by ferricena** [comment]
I found the error, it did not find the file because in the system the name is wsus_miner.ps1.ps1, but now when running it gives the following error:

File C:\zabbix-agent\scripts\wsus_miner.ps1 cannot be loaded. The file 
C:\zabbix-agent\scripts\wsus_miner.ps1 is not digitally signed. You cannot run 
this script on the current system. For more information about running scripts 
and setting execution policy, see about_Execution_Policies at 
http://go.microsoft.com/fwlink/?LinkID=135170.
    + CategoryInfo          : SecurityError: (:) [], ParentContainsErrorRecord 
   Exception
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by alapco** [comment]
Check witch execution policy you need where the ps1 is being executed, usually is RemoteSigned but you will probably need to change it.

Open a new powershell console and execute **Set-ExecutionPolicy -ExecutionPolicy Unrestricted**, then try to execute the ps1 again.

Note that this is not an execution policy to apply at production environments.
