### ISSUE TITLE
Count only the approved updates

### ISSUE THREAD

**Issue by musklor** [zbx-sadman/WSUS#5]
Hello, I tried your scripts and template and my manager love it.
I think we could improve the script in order to count only the approved updates per group. (Neededupdates)

**Comment by musklor** [comment]
I have some Citrix servers and I don't want to count the non approved updates. (ComputerNeededupdates)
I can't deny updates, they are used by another servers.

https://get-mailbox.net/get-wsusreport

$NeededUpdate = $ComputerTargetToUpdate.GetUpdateInstallationInfoPerUpdate() `
			| where {
				($_.UpdateApprovalAction -eq "install") -and `
				(($_.UpdateInstallationState -eq "downloaded") -or `
				($_.UpdateInstallationState -eq "notinstalled"))
			}

**Comment by zbx-sadman** [comment]
Hello

This problem is not exactly clear for me.  Some years ago i compare numbers from the output of my script, and numbers from the WSUS console and all was OK.  Unfortunately, i do not remember where i saw rules of host state detection... But i affraid that condition changes will broke whole harmony ;)

May be need to make some kind of virtual key... like 'ApprovedButNotInstalled' ?

**Comment by musklor** [comment]
Édit : ok I found a solution, I'll post the code tomorrow.

Yes I'm agree with you. I tried update scopes but no chance.
Approvedbutnotinstalled could be a great idea.
Or GetTotalSummaryApprovedPerComputerTarget
Do you think it's possible? Easier with poshwsus?

My coworker made me a proposition : a new WSUS server.... Just for the Citrix servers.

About GetTotalSummaryPerComputerTarget : Gets the summary information for updates of the specified type for computers in this computer target group. Updates with at least one approval are included, even if the update is not approved for this particular target group.

I have an idea with this script : https://github.com/proxb/PoshWSUS/blob/master/Scripts/Get-PSWSUSUpdatePerClient.ps1

**Comment by musklor** [comment]
Here it is 👍 

Dirty code, sorry

            'ComputerTargetsNeedingUpdates' {
                # Include no failed, but not installed, downloaded, pending reboot computers
                $UpdateScope = New-Object Microsoft.UpdateServices.Administration.UpdateScope
				$ComputerScope = New-Object Microsoft.UpdateServices.Administration.ComputerTargetScope
				$MemberOfGroup = $wsus.getComputerTargetGroup($ComputerTargetGroups.Id).GetComputerTargets()
				$MemberOfGroup | select fulldomainname, 
				@{name="failedCount";expression={($_.GetupdateInstallationInfoPerupdate($updatescope) | where {($_.updateinstallationstate -like 'failed')}).count}},
				@{name="NotInstalledCount";expression={($_.GetupdateInstallationInfoPerupdate($updatescope) | where {($_.updateinstallationstate -like 'Notinstalled') -and ($_.UpdateApprovalAction -eq "install")}).count}},
				@{name="DownloadedCount";expression={($_.GetupdateInstallationInfoPerupdate($updatescope) | where {($_.updateinstallationstate -like 'Downloaded')}).count}},
				@{name="InstalledPendingRebootCount";expression={($_.GetupdateInstallationInfoPerupdate($updatescope) | where {($_.updateinstallationstate -like 'InstalledPendingReboot')}).count}
				} | Where { (0 -eq $_.FailedCount) -And (0 -ne ($_.NotInstalledCount+$_.DownloadedCount+$_.InstalledPendingRebootCount)) };						
				#$ComputerTargetGroups | % { $_.GetTotalSummaryPerComputerTarget() } |
                  
			}

**Comment by zbx-sadman** [comment]
Now i have no time to dive again to MSDN and WSUS classes for free. May be later.

**Comment by musklor** [comment]
Thanks for your time but my client use another product right now so it's not a priority anymore. Thanks for the answer and all your work
